name: Ejecutar Bot de Apuestas
on:
  schedule:
    - cron: '*/30 15-22 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Instalar libreria
        run: pip install requests
      - name: Test de Envio Directo
        run: |
          python -c '
          import requests
          res = requests.post("https://telegram.org", json={"chat_id": "524615075", "text": "🚀 *¡CONEXIÓN EN LA NUBE CONFIRMADA!* 🚀\n\nSi lees esto, tu bot ya recibe las alertas en vivo sin problemas.", "parse_mode": "Markdown"})
          print("Servidor responde:", res.text)
          '
